services:
  backend:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - ../frontend/dist:/app/public
  # worker:
  #   build: .
  #   container_name: worker-process
  #   command: npm run startWorker
  #   depends_on:
  #     - redis
  #   environment:
  #     - NODE_ENV=development
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=raj
      - ME_CONFIG_BASICAUTH_PASSWORD=me
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  mongo-data: 
    driver: local
  redis-data:
    driver: local